### ISSUE TITLE
Permission denied when trying to use apt-get install

### ISSUE THREAD

**Issue by phil-chp** [turtlebrowser/get-conan#8]
Hey,

I'm not sure if this is an issue with this `turtlebrowser/get-conan@main`, I'm mostly looking for help trying to get this to work.

I'm working with the `ubuntu-latest` container. Conan ends up finding missing dependencies before even starting to fetch the dependencies for my project, these are `libgtk2.0-dev`, `libva-dev`, `libvdpau-dev`, etc. The problem is when it tries to fetch these and install them using `apt-get install` it doesn't have permissions and just crashes.

I tried the clean approach, of manually giving it the necessary dependencies `sudo apt install libgtk2.0-dev ... (about 30 different libs)`, this eventually got nowhere, because conan tried to `apt-get update` or something like that, even if it finds all it's dependencies. So it always ends up crashing due to: `E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)`, below are the logs for the first step (which is `libgtk2.0-dev` missing):
```
gtk/system: RUN: dpkg-query -W -f='${Status}' libgtk2.0-dev | grep -q "ok installed"
dpkg-query: no packages found matching libgtk2.0-dev
gtk/system: RUN: apt-get update
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
ERROR: gtk/system: Error in system_requirements() method, line 39
  apt.install(["libgtk2.0-dev"] if self.options.version == 2 else ["libgtk-3-dev"], update=True, check=True)
  ConanException: Command 'apt-get update' failed
Error: Process completed with exit code 1.
```

So you would think giving it sudo would work, `sudo conan install ..` just doesn't find conan, so instead passing `sudo $(which conan) install ...` works, to some extent:
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/conan", line 5, in <module>
    from conans.conan import run
ModuleNotFoundError: No module named 'conans'
Error: Process completed with exit code 1.
```

Conan doesn't seem to like to be ran as sudo, so I'm stuck... Here is a minimal version of my github action yml config:
```yml
name: Build and test

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y g++ cmake lcov

    - name: Conan Install
      run: |
        conan profile detect 2>/dev/null || true
        conan install . --output-folder=build/conan/ --build=missing --settings=build_type=${{env.BUILD_TYPE}} -s compiler.cppstd=gnu20 -c tools.system.package_manager:mode=install
```

Could my problem come from all the parameters passed to `conan install` ? Yes, they are all necessary for my case.

Thank you very much in advance! If you need any other info, I would gladly help with that.
